# File: .github/workflows/deployment.yml

name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and push backend Docker image
        run: |
          az acr login --name myregistry
          docker build -t myregistry.azurecr.io/backend:latest ./backend
          docker push myregistry.azurecr.io/backend:latest
      
      - name: Build and push frontend Docker image
        run: |
          docker build -t myregistry.azurecr.io/frontend:latest ./frontend
          docker push myregistry.azurecr.io/frontend:latest
      
      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --name voice-analyzer-api --resource-group voice-analyzer-rg --docker-custom-image-name myregistry.azurecr.io/backend:latest
          az webapp config container set --name voice-analyzer-ui --resource-group voice-analyzer-rg --docker-custom-image-name myregistry.azurecr.io/frontend:latest
